spring: 
  profiles: 
    active: dev
---
server: 
  port: 8208
spring: 
  application: 
    name: consume-user
  profiles: dev  
eureka: 
  instance: 
    prefer-ip-address: true  #注册服务的时候使用服务的ip地址
  client: 
    service-url: 
       defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
feign: 
  hystrix: 
    enabled: true
---
server: 
  port: 8206
spring: 
  application: 
    name: consume-user
  profiles: prod  
eureka: 
  instance: 
    prefer-ip-address: true  #注册服务的时候使用服务的ip地址
  client: 
    service-url: 
       defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/,http://eureka3:7003/eureka/
feign: 
  hystrix: 
    enabled: true